### ISSUE TITLE
Could not find  in your load path (RuntimeError)

### ISSUE THREAD

**Issue by ericbrooke** [assaf/vanity#261]
Had warning: circular argument reference - score #259 

Fixed by upgrading to latest beta.  Now I Have 

```
rspec
Coverage report generated for RSpec to /Users/ericbrooke/dev/qcentral/coverage. 0.0 / 0.0 LOC (100.0%) covered.
/Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/vanity-2.0.0.beta7/lib/vanity/adapters/abstract_adapter.rb:14:in `rescue in establish_connection': Could not find  in your load path (RuntimeError)
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/vanity-2.0.0.beta7/lib/vanity/adapters/abstract_adapter.rb:11:in `establish_connection'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/vanity-2.0.0.beta7/lib/vanity/playground.rb:363:in `establish_connection'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/vanity-2.0.0.beta7/lib/vanity/playground.rb:344:in `establish_connection'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/vanity-2.0.0.beta7/lib/vanity/playground.rb:423:in `autoconnect'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/vanity-2.0.0.beta7/lib/vanity/playground.rb:51:in `initialize'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/vanity-2.0.0.beta7/lib/vanity/playground.rb:441:in `new'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/vanity-2.0.0.beta7/lib/vanity/playground.rb:441:in `playground'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/vanity-2.0.0.beta7/lib/vanity/frameworks/rails.rb:4:in `load!'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/vanity-2.0.0.beta7/lib/vanity/frameworks.rb:6:in `block in <class:Plugin>'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/ericbrooke/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/ericbrooke/dev/qcentral/config/environment.rb:5:in `<top (required)>'
	from /Users/ericbrooke/dev/qcentral/spec/rails_helper.rb:4:in `require'
	from /Users/ericbrooke/dev/qcentral/spec/rails_helper.rb:4:in `<top (required)>'
	from /Users/ericbrooke/dev/qcentral/spec/controllers/albums_controller_spec.rb:1:in `require'
	from /Users/ericbrooke/dev/qcentral/spec/controllers/albums_controller_spec.rb:1:in `<top (required)>'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/bin/rspec:23:in `load'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/bin/rspec:23:in `<main>'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ericbrooke/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by phillbaker** [comment]
Hm...based on your config in https://github.com/assaf/vanity/issues/259#issuecomment-116107234, I think it's because an adapter isn't specified in the test environment. Which is weird, because your test env config is what we recommend in the readme.

Can you try:
```
test:
  collecting: false
  adapter: redis
```

**Comment by ericbrooke** [comment]
@phillbaker good call.  It now works I will rec. changes to the documentation.  Thanks for your help :-)

**Comment by ericbrooke** [comment]
Update to documentation https://github.com/assaf/vanity/pull/263
