### ISSUE TITLE
NoMethodError: undefined method `set_experiment_created_at' for nil:NilClass

### ISSUE THREAD

**Issue by edenisn** [assaf/vanity#338]
When I try to run ``assets:precompile``` task on production server (Rails 5.1.4, Vanity - last version), I get this error:
```
NoMethodError: undefined method `set_experiment_created_at' for nil:NilClass
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/vanity-2.2.9/lib/vanity/experiment/base.rb:156:in `save'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/vanity-2.2.9/lib/vanity/experiment/ab_test.rb:536:in `save'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/vanity-2.2.9/lib/vanity/experiment/definition.rb:21:in `define'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/vanity-2.2.9/lib/vanity/experiment/ab_test.rb:700:in `ab_test'
./experiments/expanded_coupon_code.rb:1:in `new_binding'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/vanity-2.2.9/lib/vanity/experiment/base.rb:24:in `eval'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/vanity-2.2.9/lib/vanity/experiment/base.rb:24:in `block in load'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/vanity-2.2.9/lib/vanity/experiment/base.rb:22:in `instance_eval'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/vanity-2.2.9/lib/vanity/experiment/base.rb:22:in `load'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/vanity-2.2.9/lib/vanity/playground.rb:248:in `block in set_experiments'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/vanity-2.2.9/lib/vanity/playground.rb:247:in `each'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/vanity-2.2.9/lib/vanity/playground.rb:247:in `set_experiments'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/vanity-2.2.9/lib/vanity/playground.rb:26:in `initialize'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/vanity-2.2.9/lib/vanity/vanity.rb:152:in `new'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/vanity-2.2.9/lib/vanity/vanity.rb:152:in `load!'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/vanity-2.2.9/lib/vanity/vanity.rb:142:in `playground'
/var/www/oneclass/current/config/environments/feature.rb:26:in `block (2 levels) in <top (required)>'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:67:in `block in execute_hook'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:49:in `each'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/application/finisher.rb:73:in `block in <module:Finisher>'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `public_send'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `method_missing'
/var/www/oneclass/current/config/environment.rb:7:in `<top (required)>'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/application.rb:329:in `require_environment!'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/railties-5.1.4/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/airbrake-6.2.1/lib/airbrake/rake.rb:19:in `execute'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/airbrake-6.2.1/lib/airbrake/rake.rb:19:in `execute'
/var/www/oneclass/shared/bundle/ruby/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `load'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:27:in `run'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.15.3/lib/bundler/cli.rb:365:in `exec'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.15.3/lib/bundler/cli.rb:22:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.15.3/lib/bundler/cli.rb:13:in `start'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.15.3/exe/bundle:30:in `block in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `load'
/home/ubuntu/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `<main>'
/home/ubuntu/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by phillbaker** [comment]
It looks like an adapter is not defined/found.

A bit more information would help debug this - can you share your configuration files?

**Comment by phillbaker** [comment]
Hi @edenisn follow up here, can you share your configuration files? Otherwise we're going to need to close this as not reproducable.
